apiVersion: v1
kind: Template
message: Created Apache Reverse Proxy for Artifactory.
metadata:
  name: artifactory-apache-reverse-proxy-template
  annotations:
    openshift.io/display-name: Artifactory Apache Reverse Proxy
    description: |-
      Create an Apache Reverse Proxy for Artifactory.
      This is based on the instructions from https://www.jfrog.com/confluence/display/RTF/Configuring+a+Reverse+Proxy.

      Pre Steps:
        1. Create wildcard public and private key for *.artifactory.exmaple.org or similar
        2. Generate the Apache Reverse Proxy Settings via Artifactory and check them into a Git project under the `httpd-cfg` directory
    iconClass: icon-apache
    openshift.io/documenation-url: TBD
    tags: artifactory,apache,proxy
labels:
  app: artifactory-apache-reverse-proxy
  template: artifactory-apache-reverse-proxy-template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: artifactory-apache-reverse-proxy
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: artifactory-apache-reverse-proxy
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: artifactory-apache-reverse-proxy:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: ${SOURCE_CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: httpd:2.4
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ImageChange
      imageChange:
    - type: ConfigChange
- apiVersion: v1
  kind: Secret
  metadata:
    name: artifactory-apache-reverse-proxy-tls
  type: kubernetes.io/tls
  stringData:
    tls.crt: ${TLS_CERT}
    tls.key: ${TLS_KEY}
- apiVersion: v1
  kind: Service
  metadata:
    name: artifactory-apache-reverse-proxy
  spec:
    ports:
    - name: 8443-https
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8080-http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: artifactory-apache-reverse-proxy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: artifactory-apache-reverse-proxy
  spec:
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: artifactory-apache-reverse-proxy
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: artifactory-apache-reverse-proxy
      spec:
        containers:
        - name: artifactory-apache-reverse-proxy
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/ssl
            name: tls
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: tls
          secret:
            defaultMode: 420
            secretName: artifactory-apache-reverse-proxy-tls
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - artifactory-apache-reverse-proxy
        from:
          kind: ImageStreamTag
          name: artifactory-apache-reverse-proxy:latest
    - type: ConfigChange
parameters:
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with a httpd-cfg directory containg the Apache reverse proxy configuration generated by Artifactory.
  required: True
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
  value: master
- name: SOURCE_CONTEXT_DIR
  displayName: Git Context Directory
  description: Set this to the relative path to the directory that contains the httpd-cfg directory if it is not in the root of your repository.
- name: TLS_CERT
  displayName: TLS Certificate
  description: "TLS public certificate to configure the Apache Reverse Proxy with. This should likley be a wildcard certificate matching on, for example, *.artifactory.example.org (or similar) so that the reverse proxy can proxy any number of different endpoints for Artifactory. This is the public certificate that will be served to clients accessing Artifactory via the Apache Reverse Proxy."
  required: True
- name: TLS_KEY
  displayName: TLS Key
  description: "TLS private certificate to configure the Apache Reverse Proxy with. This should likley be a wildcard certificate matching on, for example, *.artifactory.example.org (or similar) so that the reverse proxy can proxy any number of different endpoints for Artifactory. This is the private certificate that will be served to clients accessing Artifactory via the Apache Reverse Proxy."
  required: True
